apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp
spec:
  image: jhrv/testapp:latest
  port: 8080
  liveness:
    path: /ping
  readiness:
    path: /ping
  replicas:
    min: 2
    max: 4
