version: '3.8'
services:
  mkdocs:
    build:
      context: .
      args:
        PORT: 8080
    network_mode: host
    volumes:
      # The intention of this docker-compose file is to
      # permit making use of `mkdocs serve` hot-reloading
      # without turning off `--strict` flag.
      #
      # Ref: https://github.com/mkdocs/mkdocs/issues/2108
      - ./docs/:/app/docs
