name: CI

on:
  push:
    paths:
      - mkdocs.yml
      - 'docs/**'
      - pyproject.toml
      - poetry.lock

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.9
          architecture: x64

      - name: Install build tools and build documentation
        run: |
          # Install mkdocs
          pip3 install --upgrade pip
          pip3 install --no-cache-dir poetry
          poetry install --no-dev
          
          # Build docs
          poetry run mkdocs build --strict

      - if: github.ref == "refs/heads/$default-branch"
        uses: actions-hub/gcloud@318.0.0
        env:
          PROJECT_ID: aura-prod-d7e3
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICEACCOUNT_KEY_FOR_DOC_NAIS_IO_BUCKET }}
        with:
          args: -m cp -r site/* gs://doc.nais.io
          cli: gsutil
