apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: testapp
spec:
  replicas:
    min: 2
    max: 4
  ingresses: 
    - https://testapp.prod-gcp.nais.io
  env:
    - name: MY_ENVIRONMENT
      value: prod
  resources:
    limits:
      cpu: 500m 
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
